variables:
  OMP_NUM_THREADS: 8  # avoid overcommitting CPU resources

stages:
  - test

.job_template: &job_template
  stage: test
  image: pytorch/pytorch:2.3.0-cuda11.8-cudnn8-devel

test_mnist_conv:
  <<: *job_template
  script:
    - pip3 install -r requirements.txt
    - python3 -m pytest -m conv -s

test_mnist_linear:
  <<: *job_template
  script:
    - pip3 install -r requirements.txt
    - python3 -m pytest -m linear -s

test_mnist_tiled_linear:
  <<: *job_template
  script:
    - pip3 install -r requirements.txt
    - python3 -m pytest -m tiled_linear -s
