name: conv_tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test-jobs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: "rwth-i6/SynaptogenML"
          path: ""
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10.18
          cache: 'pip'
      - run: |
          pip install --upgrade pip setuptools wheel
          pip install pytest
          pip install -r requirements.txt
      - name: Test Models
        run: |
          python -m pytest tests -m conv
